services:
  app:
    build:
      dockerfile: Dockerfile-local
    container_name: express_app  
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - application

  redis:
    image: "redis:6.2.6-alpine"
    container_name: express_redis
    command: redis-server --requirepass redis
    networks:
      - application
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: express_mysql  
    volumes:
      - express-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: express
    networks:
      - application

volumes:
  express-mysql-data:


networks:
  application: